version: '3.9'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: danielvinicius/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: danielvinicius/nginx:prod
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
    name: laranet
