version: '3'

services:
  laravel:
    image: danielvinicius/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    image: danielvinicius/nginx:prod
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
